### ISSUE TITLE
Question:  mapping 

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/vault-plugin-auth-centrify#7]
When using other auths such as LDAP, you can assign groups that map the local groups to vault policies.

The readme doesn't speak towards how to map Centrify roles to policies, only on setting up an initial role to allow login.  How can someone handle this?

The goal would be to be to assign policy by role, so that users could only access secrets appropriate to them.

**Comment by jefferai** [comment]
I don't believe this plugin supports that. From looking at the code it seems like it only supports assigning the same set of policies to all users.

**Comment by nate-yocom** [comment]
@jefferai the plugin supports group aliases (role name => alias name)

@Justin-DynamicD You can do this by tying a role to a group with a group alias.

First create a group (https://www.vaultproject.io/api/secret/identity/identity-groups.html), set the type to "external", and the list of policies as you'd like.  Note the ID of the resulting group.

Next create a group alias (https://www.vaultproject.io/api/secret/identity/group-alias.html) with name identical to the Centrify Role you want projected into the group.  Set the canonical_id to the ID of the group you created previously.  Set the mount_accessor to match the Centrify plugin's accessor (see 'vault auth list' output).

Now auth using the Centrify auth plugin to have the user projected into the group alias, thereby the group, and get all associated policies.

**Comment by jefferai** [comment]
@nate-yocom Ah, thanks -- it's rare that an auth plugin has native Identity support, I didn't actually even look :-/

**Comment by jefferai** [comment]
@nate-yocom btw if you want to codify this all into the main documentation site it'd be fantastic -- we ship Centrify built-in but we don't actually have docs up on the main site for it.
